#!/usr/bin/env bash

set -e

export CF_RAISE_ERROR_ON_WARNINGS=true

#export GOPATH=~/go

rm -rf $GOPATH/pkg/*

echo `ls $GOPATH`
echo $PWD
echo `ls $PWD`

$(dirname $0)/create-cats-config
export CONFIG=$PWD/config.json
cat $CONFIG

(trap "exit 0" EXIT && go get -d github.com/cloudfoundry/cf-acceptance-tests/)
echo `ls $GOPATH`
echo $PWD
echo `ls $PWD`
export CATSPATH=$GOPATH/src/github.com/cloudfoundry/cf-acceptance-tests
echo $CATSPATH
echo `ls $CATSPATH`

rm -f $CATSPATH/gcf
curl https://s3.amazonaws.com/go-cli/builds/cf-linux-amd64 > $CATSPATH/cf
chmod u+x $CATSPATH/cf

export PATH=$CATSPATH:$PATH

cd $CATSPATH

$(dirname $0)/create-cats-config
export CONFIG=$CATSPATH/config.json

git pull
git checkout CLI-non-backwards-compatible

local_gopath=$CATSPATH/Godeps/_workspace

mkdir -p $local_gopath/bin

export GOPATH=$local_gopath:$GOPATH
export PATH=$local_gopath/bin:$PATH

go install -v github.com/onsi/ginkgo/ginkgo
echo "CATS STRAPPED WITH GATS"
ginkgo -r -slowSpecThreshold=120 -skipPackage=diego -skip="go makes the app reachable via its bound route|SSO|takes effect after a restart, not requiring a push|doesn't die when printing 32MB"
