#!/usr/bin/env bash

IP_ADDR=`cat api-address`

export API_ENDPOINT="http://api.${IP_ADDR}.xip.io"
export API="http://api.${IP_ADDR}.xip.io"
export APPS_DOMAIN="${IP_ADDR}.xip.io"
export CC_HOSTNAME="api.${IP_ADDR}.xip.io"
export BOSH_LITE_HOSTNAME="ubuntu@${IP_ADDR}"
