#!/usr/bin/env bash

set -e

if [ -z "$AWS_ACCESS_KEY_ID" ]; then
  echo "Need to set AWS_ACCESS_KEY_ID"
  exit 1
fi

if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
  echo "Need to set AWS_SECRET_ACCESS_KEY"
  exit 1
fi

root_dir=$(cd $(dirname $0) && pwd)/../..
s3_config_file=$root_dir/ci/s3cfg

file=$root_dir/cf-linux-amd64

echo s3cmd --config=$s3_config_file put $file  s3://go-cli/gocd-test/cf-linux-amd64
s3cmd --config=$s3_config_file put $file s3://go-cli/gocd-test/cf-linux-amd64
