// This file was generated by counterfeiter
package fakes

import (
	"sync"
	"github.com/cloudfoundry/cli/cf/api"
	"github.com/cloudfoundry/cli/cf/models"
)

type FakeServicePlanRepository struct {
	SearchStub        func(searchParameters map[string]string) ([]models.ServicePlan, error)
	searchMutex       sync.RWMutex
	searchArgsForCall []struct {
		searchParameters map[string]string
	}
	searchReturns struct {
		result1 []models.ServicePlan
		result2 error
	}
	UpdateStub        func(models.ServicePlan, string, bool) error
	updateMutex       sync.RWMutex
	updateArgsForCall []struct {
		arg1 models.ServicePlan
		arg2 string
		arg3 bool
	}
	updateReturns struct {
		result1 error
	}
}

func (fake *FakeServicePlanRepository) Search(searchParameters map[string]string) ([]models.ServicePlan, error) {
	fake.searchMutex.Lock()
	defer fake.searchMutex.Unlock()
	fake.searchArgsForCall = append(fake.searchArgsForCall, struct {
		searchParameters map[string]string
	}{searchParameters})
	if fake.SearchStub != nil {
		return fake.SearchStub(searchParameters)
	} else {
		return fake.searchReturns.result1, fake.searchReturns.result2
	}
}

func (fake *FakeServicePlanRepository) SearchCallCount() int {
	fake.searchMutex.RLock()
	defer fake.searchMutex.RUnlock()
	return len(fake.searchArgsForCall)
}

func (fake *FakeServicePlanRepository) SearchArgsForCall(i int) map[string]string {
	fake.searchMutex.RLock()
	defer fake.searchMutex.RUnlock()
	return fake.searchArgsForCall[i].searchParameters
}

func (fake *FakeServicePlanRepository) SearchReturns(result1 []models.ServicePlan, result2 error) {
	fake.SearchStub = nil
	fake.searchReturns = struct {
		result1 []models.ServicePlan
		result2 error
	}{result1, result2}
}

func (fake *FakeServicePlanRepository) Update(arg1 models.ServicePlan, arg2 string, arg3 bool) error {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.updateArgsForCall = append(fake.updateArgsForCall, struct {
		arg1 models.ServicePlan
		arg2 string
		arg3 bool
	}{arg1, arg2, arg3})
	if fake.UpdateStub != nil {
		return fake.UpdateStub(arg1, arg2, arg3)
	} else {
		return fake.updateReturns.result1
	}
}

func (fake *FakeServicePlanRepository) UpdateCallCount() int {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	return len(fake.updateArgsForCall)
}

func (fake *FakeServicePlanRepository) UpdateArgsForCall(i int) (models.ServicePlan, string, bool) {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	return fake.updateArgsForCall[i].arg1, fake.updateArgsForCall[i].arg2, fake.updateArgsForCall[i].arg3
}

func (fake *FakeServicePlanRepository) UpdateReturns(result1 error) {
	fake.UpdateStub = nil
	fake.updateReturns = struct {
		result1 error
	}{result1}
}

var _ api.ServicePlanRepository = new(FakeServicePlanRepository)
