// This file was generated by counterfeiter
package fakes

import (
	"sync"
	"github.com/cloudfoundry/cli/cf/api"
	"github.com/cloudfoundry/cli/cf/models"
)

type FakeUserProvidedServiceInstanceRepository struct {
	CreateStub        func(name, drainUrl string, params map[string]interface{}) (apiErr error)
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		name     string
		drainUrl string
		params   map[string]interface{}
	}
	createReturns struct {
		result1 error
	}
	UpdateStub        func(serviceInstance models.ServiceInstance) (apiErr error)
	updateMutex       sync.RWMutex
	updateArgsForCall []struct {
		serviceInstance models.ServiceInstance
	}
	updateReturns struct {
		result1 error
	}
}

func (fake *FakeUserProvidedServiceInstanceRepository) Create(name string, drainUrl string, params map[string]interface{}) (apiErr error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		name     string
		drainUrl string
		params   map[string]interface{}
	}{name, drainUrl, params})
	if fake.CreateStub != nil {
		return fake.CreateStub(name, drainUrl, params)
	} else {
		return fake.createReturns.result1
	}
}

func (fake *FakeUserProvidedServiceInstanceRepository) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeUserProvidedServiceInstanceRepository) CreateArgsForCall(i int) (string, string, map[string]interface{}) {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return fake.createArgsForCall[i].name, fake.createArgsForCall[i].drainUrl, fake.createArgsForCall[i].params
}

func (fake *FakeUserProvidedServiceInstanceRepository) CreateReturns(result1 error) {
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeUserProvidedServiceInstanceRepository) Update(serviceInstance models.ServiceInstance) (apiErr error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.updateArgsForCall = append(fake.updateArgsForCall, struct {
		serviceInstance models.ServiceInstance
	}{serviceInstance})
	if fake.UpdateStub != nil {
		return fake.UpdateStub(serviceInstance)
	} else {
		return fake.updateReturns.result1
	}
}

func (fake *FakeUserProvidedServiceInstanceRepository) UpdateCallCount() int {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	return len(fake.updateArgsForCall)
}

func (fake *FakeUserProvidedServiceInstanceRepository) UpdateArgsForCall(i int) models.ServiceInstance {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	return fake.updateArgsForCall[i].serviceInstance
}

func (fake *FakeUserProvidedServiceInstanceRepository) UpdateReturns(result1 error) {
	fake.UpdateStub = nil
	fake.updateReturns = struct {
		result1 error
	}{result1}
}

var _ api.UserProvidedServiceInstanceRepository = new(FakeUserProvidedServiceInstanceRepository)
